export const items = [
  "General",
  "Sales Package",
  "Model Number",
  "Part Number",
  "Model Name",
  "Series",
  "Color",
  "Type",
  "Suitable For",
  "Battery Backup",
  "Power Supply",
  "Battery Cell",
  "Processor And Memory Features",
  "Dedicated Graphic Memory Type",
  "Dedicated Graphic Memory Capacity",
  "Processor Brand",
  "Processor Name",
  "Processor Generation",
  "SSD",
  "RAM",
  "RAM Type",
  "HDD Capacity",
  "Processor Variant",
  "Clock Speed",
  "Memory Slots",
  "Expandable Memory",
  "Cache",
  "RPM",
  "Graphic Processor",
  "Operating System",
  "OS Architecture",
  "Operating System",
  "System Architecture",
  "Port And Slot Features",
  "Mic In",
  "RJ45",
  "USB Port",
  "HDMI Port",
  "Multi Card Slot",
  "Hardware Interface",
  "Display And Audio Features",
  "Touchscreen",
  "Screen Size",
  "Screen Resolution",
  "Screen Type",
  "Speakers",
  "Internal Mic",
  "Sound Properties",
  "Connectivity Features",
  "Wireless LAN",
  "Bluetooth",
  "Ethernet",
  "Dimensions",
  "Weight",
  "Additional Features",
  "Disk Drive",
  "Web Camera",
  "Read/Write Speed",
  "Keyboard",
  "Pointer Device",
  "Warranty",
  "Warranty Summary",
  "Warranty Service Type",
  "Covered in Warranty",
  "Not Covered in Warranty",
  "Domestic Warranty"
];
